name: Test with pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test_py38:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install optional dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest "jax[cpu]" flax torch tensorflow einops mlx dask
    - uses: actions/checkout@v3
    - name: Test with pytest
      run: |
        pip install .
        EINX_FILTER_TRACEBACK=0 pytest

  test_py310:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install optional dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest "jax[cpu]" flax dm-haiku torch tensorflow einops equinox mlx dask
        pip install --upgrade keras
    - uses: actions/checkout@v3
    - name: Test with pytest
      run: |
        pip install .
        EINX_FILTER_TRACEBACK=0 pytest
        pip install --upgrade "torch==2.2.0"
        EINX_FILTER_TRACEBACK=0 pytest
        pip install --upgrade "torch==2.1.0"
        EINX_FILTER_TRACEBACK=0 pytest
        pip install --upgrade "torch==2.0.0"
        EINX_FILTER_TRACEBACK=0 pytest